// see http://distingquickguide.rustle.works/
// see http://www.vo1t.com/Euro/Illustrated/ESdistingMk4V4.9.pdf
// see https://www.expert-sleepers.co.uk/downloads/manuals/disting_user_manual_4.20.pdf

const int wordsPerPatch = 21;
const char *allWords[] = {
    /* patch */ "A1", "", "",
    /* title */ "Precision", "Adder", "",
    /*   Z   */ "Offset", "", "",
    /*   X   */ "Pitch CV", "Input", "",
    /*   Y   */ "Inverting", "Input", "",
    /*   A   */ "CV OUT", "", "",
    /*   B   */ "Inverted", "CV OUT", "(if Y)",

    /* patch */ "A2", "", "",
    /* title */ "Four", "Quadrant", "Multiplier",
    /*   Z   */ "Scale", "", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Modulating", "CV", "Input",
    /*   A   */ "Audio Out", "(X * Y", "* scale)",
    /*   B   */ "Inverted", "Output", "of A",

    /* patch */ "A3", "", "",
    /* title */ "Full", "Wave", "Rectifier",
    /*   Z   */ "Mode", "", "",
    /*   X   */ "input", "", "",
    /*   Y   */ "Input", "", "",
    /*   A   */ "Output", "abs(X) or", "abs(X+Y)",
    /*   B   */ "Output", "abs(Y) or", "abs(X-Y)",

    /* patch */ "A4", "", "",
    /* title */ "Minimum", "maximum", "",
    /*   Z   */ "Gate", "", "",
    /*   X   */ "input", "", "",
    /*   Y   */ "input", "", "",
    /*   A   */ "Output", "min(X,Y)", "",
    /*   B   */ "Output", "max(X,Y)", "",

    /* patch */ "A5", "", "",
    /* title */ "Linear", "Exponen.", "Converter",
    /*   Z   */ "Tuning", "", "",
    /*   X   */ "Exponen", "tial", "Input",
    /*   Y   */ "Linear", "Input", "",
    /*   A   */ "Exponen", "tial", "Output",
    /*   B   */ "Linear", "Output", "",

    /* patch */ "A6", "", "",
    /* title */ "Quantizer", "", "",
    /*   Z   */ "Scale", "Select", "",
    /*   X   */ "Voltage", "Input", "",
    /*   Y   */ "Trigger/", "Transpo", "se",
    /*   A   */ "Quantiz", "ed Out", "",
    /*   B   */ "GateOut", "Note", "Cange",

    /* patch */ "A7", "", "",
    /* title */ "Comparat-", "or", "",
    /*   Z   */ "Hysteresis", "", "",
    /*   X   */ "Input", "", "",
    /*   Y   */ "Input", "", "",
    /*   A   */ "if X > Y", "then", "Gate Out",
    /*   B   */ "if X < Y", "then", "Gate Out",

    /* patch */ "A8", "", "",
    /* title */ "Dual", "Wave-", "shaper",
    /*   Z   */ "Wave", "Algorithm", "",
    /*   X   */ "Input", "Wave 1", "",
    /*   Y   */ "Input", "Wave 2", "",
    /*   A   */ "Output", "Wave 1", "",
    /*   B   */ "Output", "Wave 2", "",

    /* patch */ "B1", "", "",
    /* title */ "Sample", "& Hold", "",
    /*   Z   */ "Slew", "Rate", "/ Glide",
    /*   X   */ "CV Sample", "Input", "",
    /*   Y   */ "CV", "Gate", "Input",
    /*   A   */ "Sampled", "CV", "Output",
    /*   B   */ "Noise", "Output", "",

    /* patch */ "B2", "", "",
    /* title */ "Slew", "Rate", "Limiter",
    /*   Z   */ "Slew", "Rate", "",
    /*   X   */ "Input", "", "",
    /*   Y   */ "Input", "", "",
    /*   A   */ "Linear", "Slew", "",
    /*   B   */ "Logarit.", "Slew", "",

    /* patch */ "B3", "", "",
    /* title */ "Pitch &", "Envelope", "Tracker",
    /*   Z   */ "Envelo", "pe Rate", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Pitch", "Modula", "tor",
    /*   A   */ "1 V / Oct", "Input", "",
    /*   B   */ "Envelo", "pe Out", "",

    /* patch */ "B4", "", "",
    /* title */ "Clockable", "Delay/", "Echo",
    /*   Z   */ "Feedback", "", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Clock", "Input", "",
    /*   A   */ "Mix /", "Mix /", "Delay",
    /*   B   */ "Delay/", "Mix /", "Delay",

    /* patch */ "B5", "", "",
    /* title */ "LFO", "", "",
    /*   Z   */ "Tune", "", "",
    /*   X   */ "Hz / V", "Frequency", "",
    /*   Y   */ "wave-", "shape", "",
    /*   A   */ "saw ->", "sine ->", "triangle",
    /*   B   */ "pulse->", "square->", "pulse",

    /* patch */ "B6", "", "",
    /* title */ "Clockable", "LFO", "",
    /*   Z   */ "integer", "multiplier", "/divider",
    /*   X   */ "Clock", "Input", "",
    /*   Y   */ "Wave-", "shape", "",
    /*   A   */ "saw ->", "sine ->", "triangle",
    /*   B   */ "pulse->", "square->", "pulse",

    /* patch */ "B7", "", "",
    /* title */ "VCO with", "linear", "FM",
    /*   Z   */ "Tune", "+ / - 0.5", "Octaves",
    /*   X   */ "1 V / Oct", "Pitch", "Input",
    /*   Y   */ "Linear", "FM", "Input",
    /*   A   */ "Sine", "Output", "",
    /*   B   */ "Sawtooth", "Output", "",

    /* patch */ "B8", "", "",
    /* title */ "VCO", "with wave-", "shaping",
    /*   Z   */ "Tune", "+ / - 0.5", "Octaves",
    /*   X   */ "1 V / Oct", "Pitch", "Input",
    /*   Y   */ "+ / - 5V", "waveshpe", "/ PWM",
    /*   A   */ "selectable", "Output", "wavefrms",
    /*   B   */ "selectable", "Output", "wavefrms",

    /* patch */ "C1", "", "",
    /* title */ "Precision", "Adder", "fract offst",
    /*   Z   */ "Offset", "", "",
    /*   X   */ "Input", "", "",
    /*   Y   */ "Input", "", "",
    /*   A   */ "Output", "X + Y +", "Offset",
    /*   B   */ "Output", "X + Y -", "Offset",

    /* patch */ "C2", "", "",
    /* title */ "VoltCntrld", "Delay", "Line",
    /*   Z   */ "Feedback", "Bipolar", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "0 - 8V", "Delay", "Time",
    /*   A   */ "Audio Out", "Delay", "Only",
    /*   B   */ "Audio Out", "X+Delay", "",

    /* patch */ "C3", "", "",
    /* title */ "Clockable", "PingPong", "Delay",
    /*   Z   */ "Feedback", "", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Clock", "> 1 Volt", "",
    /*   A   */ "Audio Out", "Left", "",
    /*   B   */ "Audio Out", "Right", "",

    /* patch */ "C4", "", "",
    /* title */ "Clockable", "PingPong", "Delay",
    /*   Z   */ "Input", "Pan", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Clock", "> 1 Volt", "",
    /*   A   */ "Audio Out", "Left", "",
    /*   B   */ "Audio Out", "Right", "",

    /* patch */ "C5", "", "",
    /* title */ "Resonator", "", "",
    /*   Z   */ "Gain", "", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "1 V / Oct", "Input", "",
    /*   A   */ "Audio Out", "", "",
    /*   B   */ "Envelope", "of Audio", "Output",

    /* patch */ "C6", "", "",
    /* title */ "Vocoder", "", "",
    /*   Z   */ "Decay", "Time", "",
    /*   X   */ "Modulat", "or Input", "",
    /*   Y   */ "Source", "Carier", "Input",
    /*   A   */ "Audio Out", "", "",
    /*   B   */ "Envelope", "of Audio", "Output",

    /* patch */ "C7", "", "",
    /* title */ "Phaser", "", "",
    /*   Z   */ "Bipolar", "Feedback", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Sweep", "Phase", "Shift",
    /*   A   */ "Audio Out", "X +", "Phaser",
    /*   B   */ "Audio Out", "Phaser", "only",

    /* patch */ "C8", "", "",
    /* title */ "Bit", "Crusher", "",
    /*   Z   */ "Bit Redu", "ction", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Sample", "Rate", "",
    /*   A   */ "Audio Out", "", "",
    /*   B   */ "Comper", "ator Out", "",

    /* patch */ "D1", "", "",
    /* title */ "DJ", "Filter", "",
    /*   Z   */ "Filter", "Sweep", "",
    /*   X   */ "Audio", "Input", "Left",
    /*   Y   */ "Audio", "Input", "Right",
    /*   A   */ "Audio Out", "Left", "",
    /*   B   */ "Audio Out", "Right", "",

    /* patch */ "D2", "", "",
    /* title */ "Tape", "Delay", "",
    /*   Z   */ "Feedback", "", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Tape", "Speed", "",
    /*   A   */ "Audio Out", "Mix or", "Delay",
    /*   B   */ "Audio Out", "Mix or", "Delay",

    /* patch */ "D3", "", "",
    /* title */ "Waveform", "Animator", "",
    /*   Z   */ "Separation", "", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Center", "Treshold", "",
    /*   A   */ "Animated", "Out", "",
    /*   B   */ "Square", "Waves", "Out",

    /* patch */ "D4", "", "",
    /* title */ "State", "Variable", "Filter",
    /*   Z   */ "Blend", "Filter", "Type",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Frequency", "1 V / Oct", "Input",
    /*   A   */ "LP<BP>HP", "Filtered", "Output",
    /*   B   */ "HP<BP>LP", "Filtered", "Output",

    /* patch */ "D5", "", "",
    /* title */ "LP / HP", "Filter", "",
    /*   Z   */ "Resona", "nce", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Frequency", "1 V / Oct", "Input",
    /*   A   */ "Low Pass", "Audio Out", "",
    /*   B   */ "High Pass", "Audio Out", "",

    /* patch */ "D6", "", "",
    /* title */ "LP / BP", "Filter", "",
    /*   Z   */ "Resona", "nce", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Frequency", "1 V / Oct", "Input",
    /*   A   */ "Low Pass", "Audio Out", "",
    /*   B   */ "BandPass", "Audio Out", "",

    /* patch */ "D7", "", "",
    /* title */ "BP / HP", "Filter", "",
    /*   Z   */ "Resona", "nce", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Frequency", "1 V / Oct", "Input",
    /*   A   */ "BandPass", "Audio Out", "",
    /*   B   */ "High Pass", "Audio Out", "",

    /* patch */ "D8", "", "",
    /* title */ "BP / Notch", "Filter", "",
    /*   Z   */ "Resona", "nce", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Frequency", "1 V / Oct", "Input",
    /*   A   */ "BandPass", "Audio Out", "",
    /*   B   */ "Notch", "Audio Out", "",

    /* patch */ "E1", "", "",
    /* title */ "AR", "Envelope", "",
    /*   Z   */ "Envelope", "Times", "",
    /*   X   */ "Trigger", "Input", "> 1 Volt",
    /*   Y   */ "Trigger", "Input", "> 1 Volt",
    /*   A   */ "Envelope", "Out", "",
    /*   B   */ "Envelope", "Out", "",

    /* patch */ "E2", "", "",
    /* title */ "AR", "Envelope", "& VCA",
    /*   Z   */ "Envelope", "Times", "",
    /*   X   */ "Trigger", "Input", "> 1 Volt",
    /*   Y   */ "VCA", "Input", "",
    /*   A   */ "Envelope", "Out", "",
    /*   B   */ "VCA", "Out", "",

    /* patch */ "E3", "", "",
    /* title */ "Dual AR", "Envelope", "",
    /*   Z   */ "Envelope", "Times", "",
    /*   X   */ "Trigger", "Input A", "> 1 Volt",
    /*   Y   */ "Trigger", "Input B", "> 1 Volt",
    /*   A   */ "Envelope", "Out", "",
    /*   B   */ "Envelope", "Out", "",

    /* patch */ "E4", "", "",
    /* title */ "Stereo", "Compressor", "",
    /*   Z   */ "Compre", "ssion", "Ratio",
    /*   X   */ "Audio", "Input", "Left",
    /*   Y   */ "Audio", "Input", "Right",
    /*   A   */ "Audio Out", "Left", "",
    /*   B   */ "Audio Out", "Right", "",

    /* patch */ "E5", "", "",
    /* title */ "Sidechain", "Compressor", "",
    /*   Z   */ "Sidechain", "Input", "",
    /*   X   */ "Audio", "Input", "Left",
    /*   Y   */ "Audio", "Input", "Right",
    /*   A   */ "Audio Out", "Left", "",
    /*   B   */ "Audio Out", "Right", "",

    /* patch */ "E6", "", "",
    /* title */ "Mono", "Compressor", "",
    /*   Z   */ "Compre", "ssion", "Ratio",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Sidechain", "Input", "",
    /*   A   */ "Audio Out", "", "",
    /*   B   */ "Gain Re-", "duction", "Output",

    /* patch */ "E7", "", "",
    /* title */ "Euro to", "Buchla", "Converter",
    /*   Z   */ "Tune", "+ / - 0.5", "Octaves",
    /*   X   */ "1 V / Oct", "Input", "",
    /*   Y   */ "Gate", "Input", "",
    /*   A   */ "1.2V/Oct", "Output", "",
    /*   B   */ "Gate /", "Trigger", "Output",

    /* patch */ "E8", "", "",
    /* title */ "Buchla", "to Euro", "Converter",
    /*   Z   */ "Tune", "+ / - 0.5", "Octaves",
    /*   X   */ "1.2V/Oct", "Input", "",
    /*   Y   */ "Gate /", "Trigger", "Input",
    /*   A   */ "1 V / Oct", "Output", "",
    /*   B   */ "Trigger", "Output", "",

    /* patch */ "F1", "", "",
    /* title */ "Clockable", "AD Envlp", "w. mute",
    /*   Z   */ "Envelope", "Shape", "",
    /*   X   */ "> 1 Volt", "Clock", "Input",
    /*   Y   */ "> 1 Volt", "Mute", "Input",
    /*   A   */ "Envelope", "Out", "",
    /*   B   */ "Envelope", "Out", "",

    /* patch */ "F2", "", "",
    /* title */ "Clockable", "AD Envlp", "w. gate",
    /*   Z   */ "Envelope", "Shape", "",
    /*   X   */ "> 1 Volt", "Clock", "Input",
    /*   Y   */ "> 1 Volt", "Gate", "Input",
    /*   A   */ "Envelope", "Out", "",
    /*   B   */ "Envelope", "Out", "",

    /* patch */ "F3", "", "",
    /* title */ "Clockable", "AD Envlp", "w. trigger",
    /*   Z   */ "Envelope", "Shape", "",
    /*   X   */ "> 1 Volt", "Clock", "Input",
    /*   Y   */ "> 1 Volt", "Trigger", "Input",
    /*   A   */ "Envelope", "Out", "",
    /*   B   */ "Envelope", "Out", "",

    /* patch */ "F4", "", "",
    /* title */ "Clockable", "AD Envlp", "& VCA",
    /*   Z   */ "Envelope", "Shape", "",
    /*   X   */ "> 1 Volt", "Clock", "Input",
    /*   Y   */ "VCA", "Audio", "Input",
    /*   A   */ "Envelope", "Out", "",
    /*   B   */ "VCA", "Audio", "Output",

    /* patch */ "F5", "", "",
    /* title */ "ShiftRgistr", "Random", "CVs",
    /*   Z   */ "Random-", "ization", "",
    /*   X   */ "> 1 Volt", "Clock", "Input",
    /*   Y   */ "Flip", "Modifier", "",
    /*   A   */ "+ Volts", "Unipolar", "Output",
    /*   B   */ "+/- Volts", "Bipolar", "Output",

    /* patch */ "F6", "", "",
    /* title */ "ShiftRgistr", "Random", "QuntzdCVs",
    /*   Z   */ "Random-", "ization", "",
    /*   X   */ "> 1 Volt", "Clock", "Input",
    /*   Y   */ "Flip", "Modifier", "",
    /*   A   */ "+ Volts", "Unipolar", "Output",
    /*   B   */ "+/- Volts", "Bipolar", "Output",

    /* patch */ "F7", "", "",
    /* title */ "ShiftRgistr", "Random", "Triggers",
    /*   Z   */ "Random-", "ization", "",
    /*   X   */ "> 1 Volt", "Clock", "Input",
    /*   Y   */ "Flip", "Modifier", "",
    /*   A   */ "Trigger", "Output", "",
    /*   B   */ "Inverse", "Trigger", "Output",

    /* patch */ "F8", "", "",
    /* title */ "ShiftRgistr", "Random", "DualTrggers",
    /*   Z   */ "Random-", "ization", "",
    /*   X   */ "> 1 Volt", "Clock", "Input",
    /*   Y   */ "Flip", "Modifier", "",
    /*   A   */ "+ Volts", "Unipolar", "Output",
    /*   B   */ "+/- Volts", "Bipolar", "Output",

    /* patch */ "G1", "", "",
    /* title */ "ES-1", "Emulation", "",
    /*   Z   */ "Trim", "", "",
    /*   X   */ "Input1", "from Au", "dio Iface",
    /*   Y   */ "Input2", "from Au", "dio Iface",
    /*   A   */ "Output1", "to Modu-", "lar CV",
    /*   B   */ "Output2", "to Modu-", "lar CV",

    /* patch */ "G2", "", "",
    /* title */ "ES-2", "Emulation", "",
    /*   Z   */ "Trim", "", "",
    /*   X   */ "Input1", "from Mo", "dular CV",
    /*   Y   */ "Input2", "from Mo", "dular CV",
    /*   A   */ "Output1", "to Audio", "Interfce",
    /*   B   */ "Output2", "to Audio", "Interfce",

    /* patch */ "G3", "", "",
    /* title */ "Pitch", "Reference", "",
    /*   Z   */ "Output", "Amplitde", "",
    /*   X   */ "", "", "",
    /*   Y   */ "", "", "",
    /*   A   */ "Sine", "Wave", "Output",
    /*   B   */ "Square", "Wave", "Output",

    /* patch */ "G4", "", "",
    /* title */ "Frequency", "Reference", "",
    /*   Z   */ "Output", "Amplitde", "",
    /*   X   */ "", "", "",
    /*   Y   */ "", "", "",
    /*   A   */ "Sine", "Wave", "Output",
    /*   B   */ "Square", "Wave", "Output",

    /* patch */ "G5", "", "",
    /* title */ "Tuner", "", "",
    /*   Z   */ "Sets", "Amplitde", "of B",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "", "", "",
    /*   A   */ "Audio", "Thru", "Output",
    /*   B   */ "Sine", "Wave", "Output",

    /* patch */ "G6", "", "",
    /* title */ "Clock", "", "",
    /*   Z   */ "", "", "",
    /*   X   */ "Clock", "Input", " ",
    /*   Y   */ "Run /", "Stop", "Input",
    /*   A   */ "Clock", "Output", "",
    /*   B   */ "Clock", "Output", "",

    /* patch */ "G7", "", "",
    /* title */ "MIDI", "to CV", "Convers.",
    /*   Z   */ "", "", "",
    /*   X   */ "", "", "",
    /*   Y   */ "", "", "",
    /*   A   */ "Pitch", "CV", "Output",
    /*   B   */ "Gate", "Output", "",

    /* patch */ "G8", "", "",
    /* title */ "CV to", "MIDI", "Convers.",
    /*   Z   */ "Modwheel", "or Velo.", "CV input",
    /*   X   */ "Pitch", "CV", "Input",
    /*   Y   */ "Gate", "Input", "",
    /*   A   */ "Pass", "Through", "X",
    /*   B   */ "Pass", "Through", "Y",

    /* patch */ "H1", "", "",
    /* title */ "Crossfade", "Pan", "",
    /*   Z   */ "Crossfade", "Pan", "",
    /*   X   */ "Input", "", "",
    /*   Y   */ "Input", "", "",
    /*   A   */ "Mix of", "X & Y", "",
    /*   B   */ "inv. Mix", "of X & Y", "or LFO",

    /* patch */ "H2", "", "",
    /* title */ "Dual", "Sample", "& Hold",
    /*   Z   */ "Hold", "Gate", "",
    /*   X   */ "Sample", "Input", "for A",
    /*   Y   */ "Sampe", "Input", "for B",
    /*   A   */ "Output", "A", "",
    /*   B   */ "Output", "B", "",

    /* patch */ "H3", "", "",
    /* title */ "Dual", "Quantizer", "(Z scale)",
    /*   Z   */ "Scale", "", "",
    /*   X   */ "Pitch", "CV", "Input",
    /*   Y   */ "Pitch", "CV", "Input",
    /*   A   */ "Quantized", "CV Out", "A",
    /*   B   */ "Quantized", "CV Out", "B",

    /* patch */ "H4", "", "",
    /* title */ "Dual", "Quantizer", "",
    /*   Z   */ "Trigger", "", "",
    /*   X   */ "Pitch", "CV", "Input",
    /*   Y   */ "Pitch", "CV", "Input",
    /*   A   */ "Quantized", "CV Out", "A",
    /*   B   */ "Quantized", "CV Out", "B",

    /* patch */ "H5", "", "",
    /* title */ "Dual", "Euclidean", "Patterns",
    /*   Z   */ "Pulse", "Pattern", "2",
    /*   X   */ "Clock", "Input", "",
    /*   Y   */ "Reset", "Input", "",
    /*   A   */ "Pulse", "Output", "1",
    /*   B   */ "Pulse", "Output", "2",

    /* patch */ "H6", "", "",
    /* title */ "DualDelayd", "Pulse", "Generator",
    /*   Z   */ "Function", "", "",
    /*   X   */ "Trigger", "for A", "",
    /*   Y   */ "Trigger", "for B", "",
    /*   A   */ "Pulse", "Generator", "",
    /*   B   */ "Pulse", "Generator", "",

    /* patch */ "H7", "", "",
    /* title */ "Noise", "", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "Noise", "Output", "",
    /*   B   */ "Noise", "Output", "",

    /* patch */ "H8", "", "",
    /* title */ "Quantizer", "2", "",
    /*   Z   */ "Interval", "between", "A & B",
    /*   X   */ "Pitch", "CV", "Input",
    /*   Y   */ "Trggr or", "PitchCV", "Input",
    /*   A   */ "Quantized", "CV Out", "",
    /*   B   */ "Quantized", "CV Out", "",

    /* patch */ "I1", "", "",
    /* title */ "Audio", "Playback", "",
    /*   Z   */ "Sample", "Select", "",
    /*   X   */ "CV IN", "Retrigger", "",
    /*   Y   */ "CV IN", "Start", "Position",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "I2", "", "",
    /* title */ "Clocked", "Audio", "Playback",
    /*   Z   */ "Sample", "Select", "",
    /*   X   */ "CV IN", "Retrigger", "",
    /*   Y   */ "Clock", "Input", "",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "I3", "", "",
    /* title */ "Audio", "Playback", "w. V/Oct",
    /*   Z   */ "Sample", "Select", "",
    /*   X   */ "CV IN", "Retrigger", "",
    /*   Y   */ "1 V / Oct", "CV Pitch", "Input",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "I4", "", "",
    /* title */ "Audio", "Playback", "w.Z Speed",
    /*   Z   */ "Playback", "Speed", "",
    /*   X   */ "CV IN", "Retrigger", "",
    /*   Y   */ "CV IN", "Start", "Position",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "I5", "", "",
    /* title */ "Audio", "Playback", "w.Reverse",
    /*   Z   */ "Hysteresis", "", "",
    /*   X   */ "CV IN", "Retrigger", "",
    /*   Y   */ "Input", "", "",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "I6", "", "",
    /* title */ "Audio", "Playback", "w. Scrub",
    /*   Z   */ "Sample", "Select", "",
    /*   X   */ "", "", "",
    /*   Y   */ "Playback", "Position", "",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "I7", "", "",
    /* title */ "DualAudio", "Playback", "",
    /*   Z   */ "Sample", "Select", "",
    /*   X   */ "Trigger", "for A", "",
    /*   Y   */ "Trigger", "for B", "",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "I8", "", "",
    /* title */ "DualAudio", "Playback", "w.Z Speed",
    /*   Z   */ "Playback", "Speed", "",
    /*   X   */ "Trigger", "for A", "",
    /*   Y   */ "Trigger", "for B", "",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "J1", "", "",
    /* title */ "MIDI File", "Playback", "(Clocked)",
    /*   Z   */ "MIDI File", "Select", "",
    /*   X   */ "Clock", "Input", "",
    /*   Y   */ "Retrigger", "CV Output", "",
    /*   A   */ "Pitch", "CV Output", "",
    /*   B   */ "Gate", "Output", "",

    /* patch */ "J2", "", "",
    /* title */ "Multisample", "2 Audio", "Playback",
    /*   Z   */ "Tune", "+ / - 0.5", "Octaves",
    /*   X   */ "CV IN", "Retrigger", "",
    /*   Y   */ "1 V / Oct", "Pitch Input", "",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "J3", "", "",
    /* title */ "MIDI File", "Playback", "freeRunning",
    /*   Z   */ "Playback", "Speed", "",
    /*   X   */ "1 V / Oct", "CV Speed", "",
    /*   Y   */ "Retrigger", "CV Input", "",
    /*   A   */ "Pitch", "CV Output", "",
    /*   B   */ "Gate", "Output", "",

    /* patch */ "J4", "", "",
    /* title */ "Audio", "Playback", "w. End CV",
    /*   Z   */ "EndPosition", "or Retrggr", "CV",
    /*   X   */ "Retrigger", "or Endpo-", "sition CV",
    /*   Y   */ "Start", "Position", "CV Input",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "J5", "", "",
    /* title */ "Audio", "Recorder", "",
    /*   Z   */ "RecContrl", "Z>1V: Rec", "Z<0.5:Stop",
    /*   X   */ "Audio", "Input", "Left",
    /*   Y   */ "Audio", "Input", "Right",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "J6", "", "",
    /* title */ "Multisample", "Audio", "Playback",
    /*   Z   */ "Tune", "+ / - 0.5", "Octaves",
    /*   X   */ "Retrigger", "CV Input", "",
    /*   Y   */ "1 V / Oct", "Pitch Input", "",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "J7", "", "",
    /* title */ "Mono", "Audio", "Recorder",
    /*   Z   */ "RecContrl", "Z>1V: Rec", "Z<0.5:Stop",
    /*   X   */ "Audio", "Input", "Mono",
    /*   Y   */ "", "", "",
    /*   A   */ "Audio", "Output", "Mono",
    /*   B   */ "", "", "",

    /* patch */ "J8", "", "",
    /* title */ "Audio", "Playback", "w.Crossfade",
    /*   Z   */ "Sample", "Select", "",
    /*   X   */ "Gate /", "Clock CV", "",
    /*   Y   */ "1 V / Oct", "Pitch Input", "",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "K1", "", "",
    /* title */ "Wavetable", "VCO", "",
    /*   Z   */ "Tune", "+ / - 0.5", "Octaves",
    /*   X   */ "1 V / Oct", "Pitch Input", "",
    /*   Y   */ "Wavetable", "Lookup", "Point",
    /*   A   */ "Wavetable", "VCO", "Output",
    /*   B   */ "Variable", "P3 Mode", "Output",

    /* patch */ "K2", "", "",
    /* title */ "Clockable", "Wave-", "table LFO",
    /*   Z   */ "integer", "multiplier", "/divider",
    /*   X   */ "Clock", "Input", "",
    /*   Y   */ "Wavetable", "Input", "",
    /*   A   */ "Wavetable", "Output", "",
    /*   B   */ "Wavetable", "Output", "",

    /* patch */ "K3", "", "",
    /* title */ "Wavetable", "Wave-", "shaper",
    /*   Z   */ "Gain", "", "",
    /*   X   */ "Signal", "Input", "",
    /*   Y   */ "Wavetable", "Input", "",
    /*   A   */ "Wavetable", "Output", "",
    /*   B   */ "complmtry", "Wavetable", "Output",

    /* patch */ "K4", "", "",
    /* title */ "Clockable", "Wavetable", "Envelope",
    /*   Z   */ "Trigger", "", "",
    /*   X   */ "Clock", "Input", "",
    /*   Y   */ "Wavetable", "Input", "",
    /*   A   */ "Wavetable", "Output", "",
    /*   B   */ "Wavetable", "Output", "",

    /* patch */ "K5", "", "",
    /* title */ "Prgrmable", "Quantizer", "",
    /*   Z   */ "Slew", "", "",
    /*   X   */ "Input", "", "",
    /*   Y   */ "Pitch or", "Trigger", "",
    /*   A   */ "Quantized", "(X+Y)", "",
    /*   B   */ "Trigger", "on Note", "Change",

    /* patch */ "K6", "", "",
    /* title */ "Clockable", "SD Delay", "",
    /*   Z   */ "Feedback", "", "",
    /*   X   */ "Signal", "Input", "",
    /*   Y   */ "Clock", "Input", "",
    /*   A   */ "Output", "according", "to Mode",
    /*   B   */ "Output", "according", "to Mode",

    /* patch */ "K7", "", "",
    /* title */ "Stereo", "Clockable", "SD Delay",
    /*   Z   */ "Feedback", "", "",
    /*   X   */ "Audio", "Input", "Left",
    /*   Y   */ "Audio", "Input", "Right",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "K8", "", "",
    /* title */ "Stereo", "Clockable", "SD Delay",
    /*   Z   */ "Clock", "Input", "",
    /*   X   */ "Audio", "Input", "Left",
    /*   Y   */ "Audio", "Input", "Right",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "L1", "", "",
    /* title */ "Stereo", "Reverb", "",
    /*   Z   */ "Wet / Dry", "or (press)", "freeze",
    /*   X   */ "Audio", "Input", "Left",
    /*   Y   */ "Audio", "Input", "Right",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "L2", "", "",
    /* title */ "Mono to", "Stereo", "Reverb",
    /*   Z   */ "Wet / Dry", "or (press)", "freeze",
    /*   X   */ "Audio", "Input", "Mono",
    /*   Y   */ "Feedback", "CV", "",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "L3", "", "",
    /* title */ "Dual", "Reverb", "",
    /*   Z   */ "Wet / Dry", "or (press)", "freeze",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Audio", "Input", "",
    /*   A   */ "Output", "X plus", "Reverb",
    /*   B   */ "Output", "Y plus", "Reverb",

    /* patch */ "L4", "", "",
    /* title */ "Dual", "Vowel", "Filter",
    /*   Z   */ "Vowel", "Selection", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Audio", "Input", "",
    /*   A   */ "Output", "Filtered", "X",
    /*   B   */ "Output", "Filtered", "Y",

    /* patch */ "L5", "", "",
    /* title */ "Stereo", "Chorus", "",
    /*   Z   */ "Wet / Dry", "", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "LFO", "Rate", "",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "L6", "", "",
    /* title */ "Mono", "Chorus", "",
    /*   Z   */ "Wet / Dry", "", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "LFO", "Rate", "",
    /*   A   */ "Blended", "Audio", "Output",
    /*   B   */ "Wet", "Audio", "Output",

    /* patch */ "L7", "", "",
    /* title */ "2 channel", "mono2streo", "Mixer",
    /*   Z   */ "Pan for", "Input X", "",
    /*   X   */ "Input", "", "",
    /*   Y   */ "Input", "", "",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "L8", "", "",
    /* title */ "Gate", "", "",
    /*   Z   */ "Treshold", "", "",
    /*   X   */ "Input", "Left", "",
    /*   Y   */ "Input", "Right", "",
    /*   A   */ "Output", "Left", "",
    /*   B   */ "Output", "Right", "",

    /* patch */ "M1", "", "",
    /* title */ "Delayed", "LFO", "",
    /*   Z   */ "LFO", "Speed", "",
    /*   X   */ "Trigger", "Input", "",
    /*   Y   */ "Ramp", "Time", "",
    /*   A   */ "Output", "Wave", "",
    /*   B   */ "Output", "Wave", "",

    /* patch */ "M2", "", "",
    /* title */ "Scaled", "LFO", "",
    /*   Z   */ "LFO", "Speed", "",
    /*   X   */ "min/max", "or offset", "/scale",
    /*   Y   */ "min/max", "or offset", "/scale",
    /*   A   */ "Output", "Wave", "",
    /*   B   */ "Output", "Wave", "",

    /* patch */ "M3", "", "",
    /* title */ "Logic", "", "",
    /*   Z   */ "Logical", "Operation", "for A",
    /*   X   */ "Input 1", "", "",
    /*   Y   */ "Input 2", "", "",
    /*   A   */ "Logic", "Output1", "",
    /*   B   */ "Logic", "Output2", "",

    /* patch */ "M4", "", "",
    /* title */ "Half-wave", "Rectifier", "",
    /*   Z   */ "Treshold", "", "",
    /*   X   */ "Input 1", "", "",
    /*   Y   */ "Input 2", "", "",
    /*   A   */ "Output1", "", "",
    /*   B   */ "Output2", "", "",

    /* patch */ "M5", "", "",
    /* title */ "Stereo", "Filter", "LP/HP/BP",
    /*   Z   */ "Filter", "Frequency", "",
    /*   X   */ "Audio", "Input", "Left",
    /*   Y   */ "Audio", "Input", "Right",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "M6", "", "",
    /* title */ "Stereo", "Tape", "Delay",
    /*   Z   */ "TapeSpeed", "or", "Feedback",
    /*   X   */ "Audio", "Input", "Left",
    /*   Y   */ "Audio", "Input", "Right",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "M7", "", "",
    /* title */ "Granular", "Pitch", "Shifter",
    /*   Z   */ "Mix", "or (press)", "Freeze",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "1 V / Oct", "Pitch", "Input",
    /*   A   */ "Mix", "Output", "",
    /*   B   */ "Pitch", "Shifted", "Output",

    /* patch */ "M8", "", "",
    /* title */ "Chaos", "", "",
    /*   Z   */ "Speed", "", "",
    /*   X   */ "influence", "the", "chaos",
    /*   Y   */ "influence", "the", "chaos",
    /*   A   */ "Chaotic", "Output", "",
    /*   B   */ "Chaotic", "Output", "",

    /* patch */ "N1", "", "",
    /* title */ "Switch", "", "",
    /*   Z   */ "Cntrl CV", "or", "Trigger",
    /*   X   */ "Input 1", "", "",
    /*   Y   */ "Input 2", "", "",
    /*   A   */ "Output1", "", "",
    /*   B   */ "Output2", "", "",

    /* patch */ "N2", "", "",
    /* title */ "Rotary", "", "",
    /*   Z   */ "Speed", "", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Mix", "", "",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "N3", "", "",
    /* title */ "Attenuve-", "rter/Offset", "",
    /*   Z   */ "", "", "",
    /*   X   */ "Input 1", "", "",
    /*   Y   */ "Input 2", "", "",
    /*   A   */ "X * scale", "+ offset", "",
    /*   B   */ "Y * scale", "+ offset", "",

    /* patch */ "N4", "", "",
    /* title */ "Low pass", "Gate", "",
    /*   Z   */ "Frequency", "/Strike", "",
    /*   X   */ "Audio", "Input", "Left",
    /*   Y   */ "Audio", "Input", "Right",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right",

    /* patch */ "N5", "", "",
    /* title */ "Pulsar", "VCO", "",
    /*   Z   */ "Tune", "or", "Masking",
    /*   X   */ "1 V / Oct", "Pitch In", "fundamntl",
    /*   Y   */ "1 V / Oct", "Pitch In", "formant",
    /*   A   */ "Pulsar", "Output1", "",
    /*   B   */ "Pulsar", "Output2", "",

    /* patch */ "N6", "", "",
    /* title */ "Phase", "Shifter", "",
    /*   Z   */ "Wet/Dry", "", "",
    /*   X   */ "Input", "Signal", "",
    /*   Y   */ "Phase", "Shift", "",
    /*   A   */ "Audio", "Output1", "",
    /*   B   */ "Audio", "Output2", "",

    /* patch */ "N7", "", "",
    /* title */ "Frequency", "Shifter", "",
    /*   Z   */ "Frequency", "Shift", "",
    /*   X   */ "Input", "Signal", "",
    /*   Y   */ "Frequency", "Shift", "",
    /*   A   */ "Output1", "", "",
    /*   B   */ "Output2", "", "",

    /* patch */ "N8", "", "",
    /* title */ "Clockable", "SD", "PingPong",
    /*   Z   */ "Feedback", "", "",
    /*   X   */ "Signal", "Input", "",
    /*   Y   */ "Clock", "Input", "",
    /*   A   */ "Audio", "Output", "Left",
    /*   B   */ "Audio", "Output", "Right"
};

int numPatches = 0;
int getTotalEntries() {
  while(allWords[numPatches])
  {
     numPatches++;
  }
  numPatches = numPatches/wordsPerPatch;
  return numPatches;
}
