
// see http://distingquickguide.rustle.works/
// see http://www.vo1t.com/Euro/Illustrated/ESdistingMk4V4.9.pdf
// see https://www.expert-sleepers.co.uk/downloads/manuals/disting_user_manual_4.20.pdf

const int wordsPerPatch = 21;
const char *allWords[] = {
    /* patch */ "A1", "", "",
    /* title */ "Precision", "Adder", "",
    /*   Z   */ "Offset", "", "",
    /*   X   */ "Pitch CV", "Input", "",
    /*   Y   */ "Inverting", "Input", "",
    /*   A   */ "CV OUT", "", "",
    /*   B   */ "Inverted", "CV OUT", "(if Y)",

    /* patch */ "A2", "", "",
    /* title */ "Four", "Quadrant", "Multiplier",
    /*   Z   */ "Scale", "", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Modulating", "CV", "Input",
    /*   A   */ "Audio Out", "(X * Y", "* scale)",
    /*   B   */ "Inverted", "Output", "of A",

    /* patch */ "A3", "", "",
    /* title */ "Full", "Wave", "Rectifier",
    /*   Z   */ "Mode", "", "",
    /*   X   */ "input", "", "",
    /*   Y   */ "Input", "", "",
    /*   A   */ "Output", "abs(X) or", "abs(X+Y)",
    /*   B   */ "Output", "abs(Y) or", "abs(X-Y)",

    /* patch */ "A4", "", "",
    /* title */ "Minimum", "maximum", "",
    /*   Z   */ "Gate", "", "",
    /*   X   */ "input", "", "",
    /*   Y   */ "input", "", "",
    /*   A   */ "Output", "min(X,Y)", "",
    /*   B   */ "Output", "max(X,Y)", "",

    /* patch */ "A5", "", "",
    /* title */ "Linear", "Exponen.", "Converter",
    /*   Z   */ "Tuning", "", "",
    /*   X   */ "Exponen", "tial", "Input",
    /*   Y   */ "Linear", "Input", "",
    /*   A   */ "Exponen", "tial", "Output",
    /*   B   */ "Linear", "Output", "",

    /* patch */ "A6", "", "",
    /* title */ "Quantizer", "", "",
    /*   Z   */ "Scale", "Select", "",
    /*   X   */ "Voltage", "Input", "",
    /*   Y   */ "Trigger/", "Transpo", "se",
    /*   A   */ "Quantiz", "ed Out", "",
    /*   B   */ "GateOut", "Note", "Cange",

    /* patch */ "A7", "", "",
    /* title */ "Comparat-", "or", "",
    /*   Z   */ "Hysteresis", "", "",
    /*   X   */ "Input", "", "",
    /*   Y   */ "Input", "", "",
    /*   A   */ "if X > Y", "then", "Gate Out",
    /*   B   */ "if X < Y", "then", "Gate Out",

    /* patch */ "A8", "", "",
    /* title */ "Dual", "Wave-", "shaper",
    /*   Z   */ "Wave", "Algorithm", "",
    /*   X   */ "Input", "Wave 1", "",
    /*   Y   */ "Input", "Wave 2", "",
    /*   A   */ "Output", "Wave 1", "",
    /*   B   */ "Output", "Wave 2", "",

    /* patch */ "B1", "", "",
    /* title */ "Sample", "& Hold", "",
    /*   Z   */ "Slew", "Rate", "/ Glide",
    /*   X   */ "CV Sample", "Input", "",
    /*   Y   */ "CV", "Gate", "Input",
    /*   A   */ "Sampled", "CV", "Output",
    /*   B   */ "Noise", "Output", "",

    /* patch */ "B2", "", "",
    /* title */ "Slew", "Rate", "Limiter",
    /*   Z   */ "Slew", "Rate", "",
    /*   X   */ "Input", "", "",
    /*   Y   */ "Input", "", "",
    /*   A   */ "Linear", "Slew", "",
    /*   B   */ "Logarit.", "Slew", "",

    /* patch */ "B3", "", "",
    /* title */ "Pitch &", "Envelope", "Tracker",
    /*   Z   */ "Envelo", "pe Rate", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Pitch", "Modula", "tor",
    /*   A   */ "1V / Oct", "Input", "",
    /*   B   */ "Envelo", "pe Out", "",

    /* patch */ "B4", "", "",
    /* title */ "Clockable", "Delay/", "Echo",
    /*   Z   */ "Feedbck", "", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Clock", "Input", "",
    /*   A   */ "Mix /", "Mix /", "Delay",
    /*   B   */ "Delay/", "Mix /", "Delay",

    /* patch */ "B5", "", "",
    /* title */ "LFO", "", "",
    /*   Z   */ "Tune", "", "",
    /*   X   */ "Hz / V", "Frequency", "",
    /*   Y   */ "wave-", "shape", "",
    /*   A   */ "saw ->", "sine ->", "triangle",
    /*   B   */ "pulse->", "square->", "pulse",

    /* patch */ "B6", "", "",
    /* title */ "Clockable", "LFO", "",
    /*   Z   */ "integer", "multiplier", "/divider",
    /*   X   */ "Clock", "Input", "",
    /*   Y   */ "Wave-", "shape", "",
    /*   A   */ "saw ->", "sine ->", "triangle",
    /*   B   */ "pulse->", "square->", "pulse",

    /* patch */ "B7", "", "",
    /* title */ "VCO with", "linear", "FM",
    /*   Z   */ "Tune", "+ / - 0.5", "Octaves",
    /*   X   */ "V / Oct", "Pitch", "Input",
    /*   Y   */ "Linear", "FM", "Input",
    /*   A   */ "Sine", "Output", "",
    /*   B   */ "Sawtooth", "Output", "",

    /* patch */ "B8", "", "",
    /* title */ "VCO", "with wave-", "shaping",
    /*   Z   */ "Tune", "+ / - 0.5", "Octaves",
    /*   X   */ "V / Oct", "Pitch", "Input",
    /*   Y   */ "+ / - 5V", "waveshp", "/ PWM",
    /*   A   */ "slectble", "Output", "wavefrms",
    /*   B   */ "slectble", "Output", "wavefrms",

    /* patch */ "C1", "", "",
    /* title */ "Precision", "Adder", "fract offst",
    /*   Z   */ "Offset", "", "",
    /*   X   */ "Input", "", "",
    /*   Y   */ "Input", "", "",
    /*   A   */ "Output", "X + Y +", "Offset",
    /*   B   */ "Output", "X + Y -", "Offset",

    /* patch */ "C2", "", "",
    /* title */ "VoltCntrld", "Delay", "Line",
    /*   Z   */ "Feedbck", "Bipolar", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "0 - 8V", "Delay", "Time",
    /*   A   */ "Audio Out", "Delay", "Only",
    /*   B   */ "AudioOut", "X + dlay", "",

    /* patch */ "C3", "", "",
    /* title */ "Clockable", "PingPong", "Delay",
    /*   Z   */ "Feedbck", "", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Clock", "> 1 Volt", "",
    /*   A   */ "AudioOut", "Left", "",
    /*   B   */ "AudioOut", "Right", "",

    /* patch */ "C4", "", "",
    /* title */ "Clockable", "PingPong", "Delay",
    /*   Z   */ "Input", "Pan", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Clock", "> 1 Volt", "",
    /*   A   */ "AudioOut", "Left", "",
    /*   B   */ "AudioOut", "Right", "",

    /* patch */ "C5", "", "",
    /* title */ "Resonator", "", "",
    /*   Z   */ "Gain", "", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "1 V / Oct", "Input", "",
    /*   A   */ "AudioOut", "", "",
    /*   B   */ "Envelo", "of Audio", "Output",

    /* patch */ "C6", "", "",
    /* title */ "Vocoder", "", "",
    /*   Z   */ "Decay", "Time", "",
    /*   X   */ "Modulat", "or Input", "",
    /*   Y   */ "Source", "Carier", "Input",
    /*   A   */ "AudioOut", "", "",
    /*   B   */ "Envelo", "of Audio", "Output",

    /* patch */ "C7", "", "",
    /* title */ "Phaser", "", "",
    /*   Z   */ "Bipolar", "Feedbck", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Sweep", "Phase", "Shift",
    /*   A   */ "AudioOut", "X +", "Phaser",
    /*   B   */ "AudioOut", "Phaser", "only",

    /* patch */ "C8", "", "",
    /* title */ "Bit", "Crusher", "",
    /*   Z   */ "Bit Redu", "ction", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Sample", "Rate", "",
    /*   A   */ "AudioOut", "", "",
    /*   B   */ "Comper", "ator Out", "",

    /* patch */ "D1", "", "",
    /* title */ "DJ", "Filter", "",
    /*   Z   */ "Filter", "Sweep", "",
    /*   X   */ "Audio", "Input", "Left",
    /*   Y   */ "Audio", "Input", "Right",
    /*   A   */ "AudioOut", "Left", "",
    /*   B   */ "AudioOut", "Right", "",

    /* patch */ "D2", "", "",
    /* title */ "Tape", "Delay", "",
    /*   Z   */ "Feedbck", "", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Tape", "Speed", "",
    /*   A   */ "AudioOut", "Mix or", "Delay",
    /*   B   */ "AudioOut", "Mix or", "Delay",

    /* patch */ "D3", "", "",
    /* title */ "Waveform", "Animator", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "D4", "", "",
    /* title */ "State", "Variable", "Filter",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "D5", "", "",
    /* title */ "LP / HP", "Filter", "",
    /*   Z   */ "Resona", "nce", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Freqncy", "1V / Oct", "Input",
    /*   A   */ "Low", "Pass", "AudioOut",
    /*   B   */ "High", "Pass", "AudioOut",

    /* patch */ "D6", "", "",
    /* title */ "LP / BP", "Filter", "",
    /*   Z   */ "Resona", "nce", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Freqncy", "1V / Oct", "Input",
    /*   A   */ "Low", "Pass", "AudioOut",
    /*   B   */ "Band", "Pass", "AudioOut",

    /* patch */ "D7", "", "",
    /* title */ "BP / HP", "Filter", "",
    /*   Z   */ "Resona", "nce", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Freqncy", "1V / Oct", "Input",
    /*   A   */ "Band", "Pass", "AudioOut",
    /*   B   */ "High", "Pass", "AudioOut",

    /* patch */ "D8", "", "",
    /* title */ "BP / Notch", "Filter", "",
    /*   Z   */ "Resona", "nce", "",
    /*   X   */ "Audio", "Input", "",
    /*   Y   */ "Freqncy", "1V / Oct", "Input",
    /*   A   */ "Band", "Pass", "AudioOut",
    /*   B   */ "Notch", "AudioOut", "",

    /* patch */ "E1", "", "",
    /* title */ "AR", "Envelope", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "E2", "", "",
    /* title */ "AR", "Envelope", "& VCA",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "E3", "", "",
    /* title */ "Dual AR", "Envelope", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "E4", "", "",
    /* title */ "Stereo", "Compressor", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "E5", "", "",
    /* title */ "Sidechain", "Compressor", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "E6", "", "",
    /* title */ "Mono", "Compressor", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "E7", "", "",
    /* title */ "Euro to", "Buchla", "Converter",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "E8", "", "",
    /* title */ "Buchla", "to Euro", "Converter",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "F1", "", "",
    /* title */ "Clockable", "AD Envlp", "w. mute",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "F2", "", "",
    /* title */ "Clockable", "AD Envlp", "w. gate",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "F3", "", "",
    /* title */ "Clockable", "AD Envlp", "w. trigger",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "F4", "", "",
    /* title */ "Clockable", "AD Envlp", "& VCA",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "F5", "", "",
    /* title */ "ShiftRgstr", "Random", "CVs",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "F6", "", "",
    /* title */ "ShiftRgstr", "Random", "QuntzdCVs",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "F7", "", "",
    /* title */ "ShiftRgstr", "Random", "Triggers",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "F8", "", "",
    /* title */ "ShiftRgstr", "Random", "DualTrggers",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "G1", "", "",
    /* title */ "ES-1", "Emulation", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "G2", "", "",
    /* title */ "ES-2", "Emulation", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "G3", "", "",
    /* title */ "Pitch", "Reference", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "G4", "", "",
    /* title */ "Frequency", "Reference", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "G5", "", "",
    /* title */ "Tuner", "", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "G6", "", "",
    /* title */ "Clock", "", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "G7", "", "",
    /* title */ "MIDI/CV", "", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "G8", "", "",
    /* title */ "CV/MIDI", "", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "H1", "", "",
    /* title */ "Crossfade", "Pan", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "H2", "", "",
    /* title */ "Dual", "Sample", "& Hold",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "H3", "", "",
    /* title */ "Dual", "Quantizer", "(Z scale)",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "H4", "", "",
    /* title */ "Dual", "Quantizer", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "H5", "", "",
    /* title */ "Dual", "Euclidean", "Patterns",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "H6", "", "",
    /* title */ "DualDelayd", "Pulse", "Generator",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "H7", "", "",
    /* title */ "Noise", "", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "H8", "", "",
    /* title */ "Quantizer", "2", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "I1", "", "",
    /* title */ "Audio", "Playback", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "I2", "", "",
    /* title */ "Clocked", "Audio", "Playback",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "I3", "", "",
    /* title */ "Audio", "Playback", "w. V/Oct",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "I4", "", "",
    /* title */ "Audio", "Playback", "w.Z Speed",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "I5", "", "",
    /* title */ "Audio", "Playback", "w.Reverse",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "I6", "", "",
    /* title */ "Audio", "Playback", "w. Scrub",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "I7", "", "",
    /* title */ "DualAudio", "Playback", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "I8", "", "",
    /* title */ "DualAudio", "Playback", "w.Z Speed",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "J1", "", "",
    /* title */ "MIDI File", "Playback", "(Clocked)",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "J2", "", "",
    /* title */ "Multisample", "2 Audio", "Playback",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "J3", "", "",
    /* title */ "MIDI File", "Playback", "freeRunning",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "J4", "", "",
    /* title */ "Audio", "Playback", "w. End CV",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "J5", "", "",
    /* title */ "Audio", "Recorder", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "J6", "", "",
    /* title */ "Multisample", "Audio", "Playback",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "J7", "", "",
    /* title */ "Mono", "Audio", "Recorder",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "J8", "", "",
    /* title */ "Audio", "Playback", "w.Crossfade",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "K1", "", "",
    /* title */ "Wavetable", "VCO", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "K2", "", "",
    /* title */ "Clockable", "Wave-", "table LFO",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "K3", "", "",
    /* title */ "Wavetable", "Wave-", "shaper",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "K4", "", "",
    /* title */ "Clockable", "Wavetable", "Envelope",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "K5", "", "",
    /* title */ "Prgrmable", "Quantizer", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "K6", "", "",
    /* title */ "Clockable", "SD Delay", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "K7", "", "",
    /* title */ "Stereo", "Clockable", "SD Delay",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "K8", "", "",
    /* title */ "Stereo", "Clockable", "SD Delay",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "L1", "", "",
    /* title */ "Stereo", "Reverb", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "L2", "", "",
    /* title */ "Mono to", "Stereo", "Reverb",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "L3", "", "",
    /* title */ "Dual", "Reverb", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "L4", "", "",
    /* title */ "Dual", "Vowel", "Filter",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "L5", "", "",
    /* title */ "Stereo", "Chorus", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "L6", "", "",
    /* title */ "Mono", "Chorus", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "L7", "", "",
    /* title */ "Mixer", "", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "L8", "", "",
    /* title */ "Gate", "", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "M1", "", "",
    /* title */ "Delayed", "LFO", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "M2", "", "",
    /* title */ "Scaled", "LFO", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "M3", "", "",
    /* title */ "Logic", "", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "M4", "", "",
    /* title */ "Half-wave", "Rectifier", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "M5", "", "",
    /* title */ "Stereo", "Filter", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "M6", "", "",
    /* title */ "Stereo", "Tape", "Delay",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "M7", "", "",
    /* title */ "Granular", "Pitch", "Shifter",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "M8", "", "",
    /* title */ "Chaos", "", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "N1", "", "",
    /* title */ "Switch", "", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "N2", "", "",
    /* title */ "Rotary", "", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "N5", "", "",
    /* title */ "Pulsar", "VCO", "",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "N8", "", "",
    /* title */ "Clockable", "SD", "PingPong",
    /*   Z   */ "TODO", "", "",
    /*   X   */ "TODO", "", "",
    /*   Y   */ "TODO", "", "",
    /*   A   */ "TODO", "", "",
    /*   B   */ "TODO", "", "",

    /* patch */ "X1", "", "",
    /* title */ "Fake", "1 Line", "per Algo",
    /*   Z   */ "Line 1", "", "",
    /*   X   */ "Line 1", "", "",
    /*   Y   */ "Line 1", "", "",
    /*   A   */ "Line 1", "", "",
    /*   B   */ "Line 1", "", "",

    /* patch */ "X2", "", "",
    /* title */ "Fake", "2 Lines", "per Algo",
    /*   Z   */ "Line 1", "Line 2", "",
    /*   X   */ "Line 1", "Line 2", "",
    /*   Y   */ "Line 1", "Line 2", "",
    /*   A   */ "Line 1", "Line 2", "",
    /*   B   */ "Line 1", "Line 2", "",

    /* patch */ "X3", "", "",
    /* title */ "Fake", "3 Lines", "per Algo",
    /*   Z   */ "Line 1", "Line 2", "Line 3",
    /*   X   */ "Line 1", "Line 2", "Line 3",
    /*   Y   */ "Line 1", "Line 2", "Line 3",
    /*   A   */ "Line 1", "Line 2", "Line 3",
    /*   B   */ "Line 1", "Line 2", "Line 3",

    /* patch */ "X4", "", "",
    /* title */ "Display", "Test", "All Lines",
    /*   Z   */ "EELine 1H", "EELine 2H", "EELing 3H",
    /*   X   */ "EELine 1H", "EELine 2H", "EELing 3H",
    /*   Y   */ "EELine 1H", "EELine 2H", "EELing 3H",
    /*   A   */ "EELine 1H", "EELine 2H", "EELing 3H",
    /*   B   */ "EELine 1H", "EELine 2H", "EELing 3H"

};

int numPatches = 0;
int getTotalEntries() {
  while(allWords[numPatches])
  {
     numPatches++;
  }
  numPatches = numPatches/wordsPerPatch;
  return numPatches;
}
